INSERT INTO TEAM(team_name, team_region, team_winnings)
VALUES (1'5RATFORCESTAFF', 'North America', 0),
    (2'ALPHA', 'North America', 0),
    (3'Arkosh Gaming', 'North America', 0),
    (4'B8', 'North America', 0),
    (5'felt', 'North America', 0),
    (6'nouns', 'North America', 0),
    (7'Shopify Rebellion', 'North America', 0),
    (8'Team DogChamp', 'North America', 0),
    (9'The Cut', 'North America', 0),
    (10'Thiuth Gaming', 'North America', 0),
    (11'TSM', 'North America', 0),
    (12'Wildcard Gaming', 'North America', 0),
    (13'Alliance.LATAM', 'South America', 0),
    (14'Balrogs', 'South America', 0),
    (15'beastcoast', 'South America', 0),
    (16'Dreamers Esports', 'South America', 0),
    (17'Evil Geniuses', 'South America', 0),
    (18'Infamous', 'South America', 0),
    (19'Infinity', 'South America', 0),
    (20'Keyd Stars', 'South America', 0),
    (21'Lava', 'South America', 0),
    (22'Mad Kings', 'South America', 0),
    (23'Ravens', 'South America', 0),
    (24'Thunder Awaken', 'South America', 0),
    (25'Vicious Gaming', 'South America', 0),
    (26'Alliance', 'Europe', 0),
    (27'D2 Hustlers', 'Europe', 0),
    (28'Entity', 'Europe', 0),
    (29'Gaimin Gladiators', 'Europe', 0),
    (30'Into The Breach', 'Europe', 0),
    (31'IVY', 'Europe', 0),
    (32'Level UP', 'Europe', 0),
    (33'Monaspa', 'Europe', 0),
    (34'Nigma Galaxy', 'Europe', 0),
    (35'OG', 'Europe', 0),
    (36'Team Bald Reborn', 'Europe', 0),
    (37'Team Liquid', 'Europe', 0),
    (38'Team Secret', 'Europe', 0),
    (39'Tundra Esports', 'Europe', 0),
    (40'BetBoom Team', 'CIS', 0),
    (41'cybercats', 'CIS', 0),
    (42'HellRaisers', 'CIS', 0),
    (43'HYDRA', 'CIS', 0),
    (44'Magic Hands', 'CIS', 0),
    (45'Marlerino eSports', 'CIS', 0),
    (46'Mind Games', 'CIS', 0),
    (47'Natus Vincere', 'CIS', 0),
    (48'Nemiga Gaming', 'CIS', 0),
    (49'One Move', 'CIS', 0),
    (50'Pavaga Gaming', 'CIS', 0),
    (51'PuckChamp', 'CIS', 0),
    (52'Rune Eaters', 'CIS', 0),
    (53'Team Empire Hope', 'CIS', 0),
    (54'Virtus.pro', 'CIS', 0),
    (55'Aster.Aries', 'China', 0),
    (56'EHOME', 'China', 0),
    (57'iG Vitality', 'China', 0),
    (58'Invictus Gaming', 'China', 0),
    (59'Knights', 'China', 0),
    (60'LBZS', 'China', 0),
    (61'PSG.LGD', 'China', 0),
    (62'Royal Never Give Up', 'China', 0),
    (63'Supernova', 'China', 0),
    (64'Team Aster', 'China', 0),
    (65'Vici Gaming', 'China', 0),
    (66'Xtreme Gaming', 'China', 0),
    (67'Ybb Gaming', 'China', 0),
    (68'Army Geniuses', 'Southeast Asia', 0),
    (69'Blacklist International', 'Southeast Asia', 0),
    (70'Bleed Esports', 'Southeast Asia', 0),
    (71'BOOM Esports', 'Southeast Asia', 0),
    (72'Execration', 'Southeast Asia', 0),
    (73'Fnatic', 'Southeast Asia', 0),
    (74'Geek Slate', 'Southeast Asia', 0),
    (75'Lilgun', 'Southeast Asia', 0),
    (76'Neon Esports', 'Southeast Asia', 0),
    (77'Polaris Esports', 'Southeast Asia', 0),
    (78'Talon Esports', 'Southeast Asia', 0),
    (79'Team SMG', 'Southeast Asia', 0),
    (80'Yangon Galacticos', 'Southeast Asia', 0);