-- drop all tables
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `jb240893`.`GAME_PERFORMANCE`;
DROP TABLE IF EXISTS `jb240893`.`HERO`;
DROP TABLE IF EXISTS `jb240893`.`PLAYER_TEAM_HISTORY`;
DROP TABLE IF EXISTS `jb240893`.`TEAM_GAME`;
DROP TABLE IF EXISTS `jb240893`.`PLAYER`;
DROP TABLE IF EXISTS `jb240893`.`GAME`;
DROP TABLE IF EXISTS `jb240893`.`TEAM`;
DROP TABLE IF EXISTS `jb240893`.`TOURNAMENT`;
SET FOREIGN_KEY_CHECKS = 1;
-- add all tables
CREATE TABLE TEAM (
    team_id int PRIMARY KEY AUTO_INCREMENT,
    team_name varchar(64),
    team_region varchar(32),
    team_winnings int DEFAULT 0
);
CREATE TABLE PLAYER (
    player_id int PRIMARY KEY AUTO_INCREMENT,
    player_name varchar(128) NOT NULL,
    gamer_name varchar(64) NOT NULL,
    player_role varchar(32),
    player_country varchar(32),
    player_region varchar(32),
    player_rank int,
    team_id int,
    FOREIGN KEY (team_id) REFERENCES TEAM(team_id)
);
CREATE TABLE TOURNAMENT (
    t_id int PRIMARY KEY AUTO_INCREMENT,
    t_name varchar(64) NOT NULL,
    t_date datetime NOT NULL,
    t_prize int DEFAULT 0,
    t_winner int NOT NULL,
    FOREIGN KEY (t_winner) REFERENCES TEAM(team_id)
);
CREATE TABLE GAME (
    game_id int PRIMARY KEY AUTO_INCREMENT,
    game_winner int,
    game_duration int NOT NULL,
    game_date datetime NOT NULL,
    tournament_id int,
    FOREIGN KEY (tournament_id) REFERENCES TOURNAMENT(t_id),
    FOREIGN KEY (game_winner) REFERENCES TEAM(team_id)
);
CREATE TABLE HERO (
    hero_id int PRIMARY KEY,
    hero_name varchar(32) NOT NULL UNIQUE,
    hero_main_stat varchar(16) NOT NULL,
    str_base int NOT NULL,
    str_gain float NOT NULL,
    str_30 float NOT NULL,
    agi_base int NOT NULL,
    agi_gain float NOT NULL,
    agi_30 float NOT NULL,
    int_base int NOT NULL,
    int_gain float NOT NULL,
    int_30 float NOT NULL,
    attack_type varchar(16) NOT NULL,
    attack_range int NOT NULL,
    damage_base int NOT NULL,
    armor_base int NOT NULL,
    move_speed_base int NOT NULL,
    turn_rate float NOT NULL
);
CREATE TABLE GAME_PERFORMANCE (
    gameplay_id int PRIMARY KEY AUTO_INCREMENT,
    g_kills int NOT NULL DEFAULT 0,
    g_deaths int NOT NULL DEFAULT 0,
    g_assists int NOT NULL DEFAULT 0,
    g_xpm int NOT NULL DEFAULT 0,
    g_gpm int NOT NULL DEFAULT 0,
    g_last_hits int NOT NULL DEFAULT 0,
    g_win int NOT NULL DEFAULT 0,
    player_id int NOT NULL,
    game_id int NOT NULL,
    hero_id int NOT NULL,
    FOREIGN KEY (player_id) REFERENCES PLAYER(player_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id),
    FOREIGN KEY (hero_id) REFERENCES HERO(hero_id)
);
CREATE TABLE PLAYER_TEAM_HISTORY (
    player_id int,
    team_id int,
    join_date datetime DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (player_id) REFERENCES PLAYER(player_id),
    PRIMARY KEY (player_id, team_id, join_date)
);
CREATE TABLE TEAM_GAME (
    team1_id int,
    team2_id int,
    game_id int,
    FOREIGN KEY (team1_id) REFERENCES TEAM(team_id),
    FOREIGN KEY (team2_id) REFERENCES TEAM(team_id),
    FOREIGN KEY (game_id) REFERENCES GAME(game_id),
    PRIMARY KEY (team1_id, team2_id, game_id)
);
-- insert all data
INSERT INTO TEAM(team_name, team_region, team_winnings)
VALUES ('5RATFORCESTAFF', 'North America', 0),
    ('ALPHA', 'North America', 0),
    ('Arkosh Gaming', 'North America', 0),
    ('B8', 'North America', 0),
    ('felt', 'North America', 0),
    ('nouns', 'North America', 0),
    ('Shopify Rebellion', 'North America', 0),
    ('Team DogChamp', 'North America', 0),
    ('The Cut', 'North America', 0),
    ('Thiuth Gaming', 'North America', 0),
    ('TSM', 'North America', 0),
    ('Wildcard Gaming', 'North America', 0),
    ('Alliance.LATAM', 'South America', 0),
    ('Balrogs', 'South America', 0),
    ('beastcoast', 'South America', 0),
    ('Dreamers Esports', 'South America', 0),
    ('Evil Geniuses', 'South America', 0),
    ('Infamous', 'South America', 0),
    ('Infinity', 'South America', 0),
    ('Keyd Stars', 'South America', 0),
    ('Lava', 'South America', 0),
    ('Mad Kings', 'South America', 0),
    ('Ravens', 'South America', 0),
    ('Thunder Awaken', 'South America', 0),
    ('Vicious Gaming', 'South America', 0),
    ('Alliance', 'Europe', 0),
    ('D2 Hustlers', 'Europe', 0),
    ('Entity', 'Europe', 0),
    ('Gaimin Gladiators', 'Europe', 0),
    ('Into The Breach', 'Europe', 0),
    ('IVY', 'Europe', 0),
    ('Level UP', 'Europe', 0),
    ('Monaspa', 'Europe', 0),
    ('Nigma Galaxy', 'Europe', 0),
    ('OG', 'Europe', 0),
    ('Team Bald Reborn', 'Europe', 0),
    ('Team Liquid', 'Europe', 0),
    ('Team Secret', 'Europe', 0),
    ('Tundra Esports', 'Europe', 0),
    ('BetBoom Team', 'CIS', 0),
    ('cybercats', 'CIS', 0),
    ('HellRaisers', 'CIS', 0),
    ('HYDRA', 'CIS', 0),
    ('Magic Hands', 'CIS', 0),
    ('Marlerino eSports', 'CIS', 0),
    ('Mind Games', 'CIS', 0),
    ('Natus Vincere', 'CIS', 0),
    ('Nemiga Gaming', 'CIS', 0),
    ('One Move', 'CIS', 0),
    ('Pavaga Gaming', 'CIS', 0),
    ('PuckChamp', 'CIS', 0),
    ('Rune Eaters', 'CIS', 0),
    ('Team Empire Hope', 'CIS', 0),
    ('Virtus.pro', 'CIS', 0),
    ('Aster.Aries', 'China', 0),
    ('EHOME', 'China', 0),
    ('iG Vitality', 'China', 0),
    ('Invictus Gaming', 'China', 0),
    ('Knights', 'China', 0),
    ('LBZS', 'China', 0),
    ('PSG.LGD', 'China', 0),
    ('Royal Never Give Up', 'China', 0),
    ('Supernova', 'China', 0),
    ('Team Aster', 'China', 0),
    ('Vici Gaming', 'China', 0),
    ('Xtreme Gaming', 'China', 0),
    ('Ybb Gaming', 'China', 0),
    ('Army Geniuses', 'Southeast Asia', 0),
    ('Blacklist International', 'Southeast Asia', 0),
    ('Bleed Esports', 'Southeast Asia', 0),
    ('BOOM Esports', 'Southeast Asia', 0),
    ('Execration', 'Southeast Asia', 0),
    ('Fnatic', 'Southeast Asia', 0),
    ('Geek Slate', 'Southeast Asia', 0),
    ('Lilgun', 'Southeast Asia', 0),
    ('Neon Esports', 'Southeast Asia', 0),
    ('Polaris Esports', 'Southeast Asia', 0),
    ('Talon Esports', 'Southeast Asia', 0),
    ('Team SMG', 'Southeast Asia', 0),
    ('Yangon Galacticos', 'Southeast Asia', 0);
INSERT INTO HERO(
        hero_id,
        hero_name,
        hero_main_stat,
        str_base,
        str_gain,
        str_30,
        agi_base,
        agi_gain,
        agi_30,
        int_base,
        int_gain,
        int_30,
        move_speed_base,
        armor_base,
        damage_base,
        attack_range,
        attack_type,
        turn_rate
    )
VALUES (
        1,
        'Abaddon',
        'STR',
        22,
        2.6,
        97.4,
        23,
        1.5,
        66.5,
        18,
        2,
        76,
        325,
        2.83,
        60,
        150,
        'melee',
        0.6
    ),
    (
        2,
        'Ancient Apparition',
        'INT',
        20,
        1.9,
        75.1,
        20,
        2.2,
        83.8,
        23,
        3.4,
        121.6,
        285,
        2.33,
        54,
        675,
        'ranged',
        0.6
    ),
    (
        3,
        'Anti-Mage',
        'AGI',
        21,
        1.6,
        67.4,
        24,
        2.8,
        105.2,
        12,
        1.8,
        64.2,
        310,
        4,
        57,
        150,
        'melee',
        0.6
    ),
    (
        4,
        'Arc Warden',
        'AGI',
        22,
        2.6,
        97.4,
        20,
        3,
        107,
        24,
        2.6,
        99.4,
        285,
        2.33,
        57,
        625,
        'ranged',
        0.7
    ),
    (
        5,
        'Axe',
        'STR',
        25,
        2.8,
        106.2,
        20,
        2,
        78,
        18,
        1.6,
        64.4,
        310,
        2.33,
        59,
        150,
        'melee',
        0.6
    ),
    (
        6,
        'Bane',
        'INT',
        22,
        2.5,
        94.5,
        22,
        2.5,
        94.5,
        22,
        2.5,
        94.5,
        305,
        4.67,
        61,
        400,
        'ranged',
        0.6
    ),
    (
        7,
        'Batrider',
        'INT',
        28,
        2.9,
        112.1,
        15,
        1.8,
        67.2,
        22,
        2.9,
        106.1,
        310,
        4.5,
        43,
        400,
        'ranged',
        0.9
    ),
    (
        8,
        'Beastmaster',
        'STR',
        23,
        2.9,
        107.1,
        18,
        1.6,
        64.4,
        16,
        1.9,
        71.1,
        305,
        3,
        58,
        150,
        'melee',
        0.6
    ),
    (
        9,
        'Bloodseeker',
        'AGI',
        24,
        2.7,
        102.3,
        22,
        3.1,
        111.9,
        17,
        2,
        75,
        300,
        5.67,
        63,
        150,
        'melee',
        0.6
    ),
    (
        10,
        'Bounty Hunter',
        'AGI',
        20,
        2.5,
        92.5,
        21,
        2.6,
        96.4,
        22,
        1.9,
        77.1,
        325,
        8.5,
        62,
        150,
        'melee',
        0.6
    ),
    (
        11,
        'Brewmaster',
        'STR',
        23,
        3.7,
        130.3,
        19,
        2,
        77,
        15,
        1.6,
        61.4,
        310,
        2.17,
        59,
        150,
        'melee',
        0.6
    ),
    (
        12,
        'Bristleback',
        'STR',
        22,
        2.5,
        94.5,
        17,
        1.8,
        69.2,
        14,
        2.8,
        95.2,
        295,
        3.83,
        58,
        150,
        'melee',
        0.9
    ),
    (
        13,
        'Broodmother',
        'AGI',
        18,
        3.2,
        110.8,
        19,
        3.4,
        117.6,
        18,
        2,
        76,
        285,
        3.17,
        54,
        150,
        'melee',
        0.6
    ),
    (
        14,
        'Centaur Warrunner',
        'STR',
        27,
        4,
        143,
        15,
        1,
        44,
        15,
        1.6,
        61.4,
        300,
        0.5,
        65,
        150,
        'melee',
        0.6
    ),
    (
        15,
        'Chaos Knight',
        'STR',
        22,
        3.2,
        114.8,
        18,
        1.4,
        58.6,
        18,
        1.2,
        52.8,
        325,
        5,
        81,
        150,
        'melee',
        0.6
    ),
    (
        16,
        'Chen',
        'INT',
        25,
        2,
        83,
        15,
        2.1,
        75.9,
        19,
        3.2,
        111.8,
        305,
        1.5,
        56,
        650,
        'ranged',
        0.6
    ),
    (
        17,
        'Clinkz',
        'AGI',
        16,
        2,
        74,
        22,
        2.5,
        94.5,
        18,
        2.2,
        81.8,
        290,
        3.67,
        43,
        600,
        'ranged',
        0.6
    ),
    (
        18,
        'Clockwerk',
        'STR',
        26,
        3.5,
        127.5,
        13,
        2.3,
        79.7,
        18,
        1.5,
        61.5,
        310,
        3.17,
        52,
        150,
        'melee',
        0.6
    ),
    (
        19,
        'Crystal Maiden',
        'INT',
        17,
        2.2,
        80.8,
        16,
        1.6,
        62.4,
        16,
        3.3,
        111.7,
        280,
        1.67,
        50,
        600,
        'ranged',
        0.6
    ),
    (
        20,
        'Dark Seer',
        'INT',
        22,
        2.6,
        97.4,
        19,
        1.8,
        71.2,
        21,
        2.7,
        99.3,
        295,
        5.17,
        60,
        150,
        'melee',
        0.6
    ),
    (
        21,
        'Dark Willow',
        'INT',
        20,
        2,
        78,
        18,
        1.6,
        64.4,
        21,
        3.5,
        122.5,
        290,
        2,
        56,
        475,
        'ranged',
        0.7
    ),
    (
        22,
        'Dawnbreaker',
        'STR',
        26,
        3.4,
        124.6,
        14,
        1.7,
        63.3,
        20,
        2.2,
        83.8,
        310,
        3.33,
        59,
        150,
        'melee',
        0.6
    ),
    (
        23,
        'Death Prophet',
        'INT',
        21,
        3.1,
        110.9,
        16,
        2,
        74,
        24,
        3.3,
        119.7,
        285,
        3.67,
        57,
        600,
        'ranged',
        0.8
    ),
    (
        24,
        'Disruptor',
        'INT',
        21,
        2.4,
        90.6,
        15,
        1.4,
        55.6,
        20,
        2.9,
        104.1,
        295,
        2.5,
        53,
        625,
        'ranged',
        0.6
    ),
    (
        25,
        'Doom',
        'STR',
        24,
        3.7,
        131.3,
        15,
        1.5,
        58.5,
        15,
        1.7,
        64.3,
        285,
        5.5,
        68,
        200,
        'melee',
        0.6
    ),
    (
        26,
        'Dragon Knight',
        'STR',
        21,
        3.4,
        119.6,
        16,
        2,
        74,
        18,
        1.7,
        67.3,
        310,
        2.67,
        61,
        150,
        'melee',
        0.6
    ),
    (
        27,
        'Drow Ranger',
        'AGI',
        16,
        1.9,
        71.1,
        20,
        2.9,
        104.1,
        15,
        1.4,
        55.6,
        300,
        3.33,
        56,
        625,
        'ranged',
        0.7
    ),
    (
        28,
        'Earth Spirit',
        'STR',
        22,
        3.8,
        132.2,
        17,
        2.4,
        86.6,
        20,
        2.1,
        80.9,
        290,
        2.83,
        57,
        150,
        'melee',
        0.6
    ),
    (
        29,
        'Earthshaker',
        'STR',
        22,
        3.7,
        129.3,
        12,
        1.4,
        52.6,
        18,
        2.1,
        78.9,
        315,
        4,
        59,
        150,
        'melee',
        0.9
    ),
    (
        30,
        'Elder Titan',
        'STR',
        26,
        3,
        113,
        16,
        1.8,
        68.2,
        23,
        1.6,
        69.4,
        310,
        2.67,
        59,
        150,
        'melee',
        0.6
    ),
    (
        31,
        'Ember Spirit',
        'AGI',
        22,
        2.6,
        97.4,
        22,
        3.2,
        114.8,
        20,
        2.2,
        83.8,
        300,
        2.67,
        59,
        150,
        'melee',
        0.8
    ),
    (
        32,
        'Enchantress',
        'INT',
        17,
        1.7,
        66.3,
        19,
        2.1,
        79.9,
        22,
        3.8,
        132.2,
        320,
        4.17,
        55,
        575,
        'ranged',
        0.6
    ),
    (
        33,
        'Enigma',
        'INT',
        21,
        2.5,
        93.5,
        14,
        1,
        43,
        19,
        3.6,
        123.4,
        290,
        3.33,
        49,
        500,
        'ranged',
        0.6
    ),
    (
        34,
        'Faceless Void',
        'AGI',
        20,
        2.4,
        89.6,
        19,
        3,
        106,
        15,
        1.5,
        58.5,
        300,
        4.17,
        62,
        150,
        'melee',
        0.9
    ),
    (
        35,
        'Grimstroke',
        'INT',
        21,
        2.4,
        90.6,
        18,
        1.9,
        73.1,
        25,
        3.8,
        135.2,
        290,
        3,
        50,
        600,
        'ranged',
        0.6
    ),
    (
        36,
        'Gyrocopter',
        'AGI',
        22,
        2.5,
        94.5,
        26,
        3.3,
        121.7,
        21,
        2.4,
        90.6,
        315,
        6.33,
        48,
        365,
        'ranged',
        0.6
    ),
    (
        37,
        'Hoodwink',
        'AGI',
        17,
        2,
        75,
        24,
        3.6,
        128.4,
        21,
        2.9,
        105.1,
        310,
        4,
        53,
        575,
        'ranged',
        0.9
    ),
    (
        38,
        'Huskar',
        'STR',
        20,
        3.3,
        115.7,
        10,
        1.5,
        53.5,
        18,
        1.5,
        61.5,
        295,
        0.67,
        46,
        400,
        'ranged',
        0.6
    ),
    (
        39,
        'Invoker',
        'INT',
        18,
        2.4,
        87.6,
        14,
        1.9,
        69.1,
        15,
        4.6,
        148.4,
        285,
        2.33,
        50,
        600,
        'ranged',
        0.6
    ),
    (
        40,
        'Io',
        'STR',
        17,
        3,
        104,
        14,
        1.6,
        60.4,
        23,
        1.7,
        72.3,
        320,
        3.33,
        51,
        500,
        'ranged',
        0.7
    ),
    (
        41,
        'Jakiro',
        'INT',
        25,
        2.5,
        97.5,
        15,
        1.2,
        49.8,
        26,
        3,
        113,
        290,
        3.5,
        61,
        400,
        'ranged',
        0.6
    ),
    (
        42,
        'Juggernaut',
        'AGI',
        20,
        2.2,
        83.8,
        34,
        2.8,
        115.2,
        14,
        1.4,
        54.6,
        300,
        5.67,
        54,
        150,
        'melee',
        0.6
    ),
    (
        43,
        'Keeper of the Light',
        'INT',
        18,
        2.3,
        84.7,
        15,
        1.6,
        61.4,
        23,
        3.2,
        115.8,
        320,
        2.5,
        50,
        600,
        'ranged',
        0.7
    ),
    (
        44,
        'Kunkka',
        'STR',
        24,
        3.8,
        134.2,
        14,
        1.6,
        60.4,
        18,
        1.8,
        70.2,
        315,
        4.33,
        60,
        150,
        'melee',
        0.6
    ),
    (
        45,
        'Legion Commander',
        'STR',
        25,
        3.3,
        120.7,
        18,
        1.7,
        67.3,
        20,
        2.2,
        83.8,
        330,
        3,
        64,
        150,
        'melee',
        0.6
    ),
    (
        46,
        'Leshrac',
        'INT',
        20,
        2.8,
        101.2,
        23,
        2.8,
        104.2,
        22,
        3.5,
        123.5,
        325,
        3.83,
        53,
        575,
        'ranged',
        0.6
    ),
    (
        47,
        'Lich',
        'INT',
        20,
        2.1,
        80.9,
        17,
        2,
        75,
        24,
        3.6,
        128.4,
        295,
        1.83,
        57,
        550,
        'ranged',
        0.7
    ),
    (
        48,
        'Lifestealer',
        'STR',
        25,
        2.4,
        94.6,
        19,
        2.6,
        94.4,
        15,
        1.8,
        67.2,
        320,
        4.17,
        53,
        150,
        'melee',
        0.9
    ),
    (
        49,
        'Lina',
        'INT',
        20,
        2.4,
        89.6,
        23,
        2.4,
        92.6,
        30,
        3.8,
        140.2,
        290,
        2.83,
        59,
        670,
        'ranged',
        0.6
    ),
    (
        50,
        'Lion',
        'INT',
        18,
        2.2,
        81.8,
        18,
        1.5,
        61.5,
        18,
        3.5,
        119.5,
        290,
        2,
        53,
        600,
        'ranged',
        0.8
    ),
    (
        51,
        'Lone Druid',
        'AGI',
        18,
        2.5,
        90.5,
        20,
        2.8,
        101.2,
        13,
        1.4,
        53.6,
        325,
        1.33,
        42,
        550,
        'ranged',
        0.6
    ),
    (
        52,
        'Luna',
        'AGI',
        21,
        2.2,
        84.8,
        24,
        3.4,
        122.6,
        23,
        1.9,
        78.1,
        325,
        6,
        56,
        330,
        'ranged',
        0.6
    ),
    (
        53,
        'Lycan',
        'STR',
        26,
        3.4,
        124.6,
        16,
        1.7,
        65.3,
        23,
        1.7,
        72.3,
        305,
        2.67,
        55,
        150,
        'melee',
        0.6
    ),
    (
        54,
        'Magnus',
        'STR',
        25,
        3.5,
        126.5,
        15,
        2.5,
        87.5,
        19,
        2.1,
        79.9,
        305,
        3.5,
        65,
        150,
        'melee',
        0.8
    ),
    (
        55,
        'Marci',
        'STR',
        23,
        3.6,
        127.4,
        20,
        2.4,
        89.6,
        19,
        1.9,
        74.1,
        315,
        3.33,
        60,
        150,
        'melee',
        0.9
    ),
    (
        56,
        'Mars',
        'STR',
        23,
        3.7,
        130.3,
        20,
        1.7,
        69.3,
        21,
        2.2,
        84.8,
        310,
        2.33,
        57,
        250,
        'melee',
        0.8
    ),
    (
        57,
        'Medusa',
        'AGI',
        17,
        1.5,
        60.5,
        22,
        3.4,
        120.6,
        23,
        3.4,
        121.6,
        275,
        2.67,
        54,
        600,
        'ranged',
        0.6
    ),
    (
        58,
        'Meepo',
        'AGI',
        24,
        2.5,
        96.5,
        17,
        2.2,
        80.8,
        20,
        1.9,
        75.1,
        330,
        6.83,
        52,
        150,
        'melee',
        0.7
    ),
    (
        59,
        'Mirana',
        'AGI',
        18,
        2.2,
        81.8,
        24,
        3.1,
        113.9,
        22,
        1.9,
        77.1,
        290,
        2,
        54,
        630,
        'ranged',
        0.6
    ),
    (
        60,
        'Monkey King',
        'AGI',
        18,
        2.8,
        99.2,
        22,
        3.7,
        129.3,
        20,
        1.8,
        72.2,
        300,
        5.67,
        55,
        300,
        'melee',
        0.6
    ),
    (
        61,
        'Morphling',
        'AGI',
        22,
        3,
        109,
        24,
        3.9,
        137.1,
        19,
        1.8,
        71.2,
        285,
        2,
        42,
        350,
        'ranged',
        0.7
    ),
    (
        62,
        'Naga Siren',
        'AGI',
        21,
        2.6,
        96.4,
        21,
        3.3,
        116.7,
        21,
        2,
        79,
        330,
        5.5,
        46,
        150,
        'melee',
        0.6
    ),
    (
        63,
        'Nature''s Prophet',
        'INT',
        21,
        2.6,
        96.4,
        22,
        3.6,
        126.4,
        23,
        3.7,
        130.3,
        295,
        3.67,
        60,
        600,
        'ranged',
        0.9
    ),
    (
        64,
        'Necrophos',
        'INT',
        18,
        2.3,
        84.7,
        12,
        1.3,
        49.7,
        21,
        2.7,
        99.3,
        280,
        3,
        51,
        500,
        'ranged',
        0.6
    ),
    (
        65,
        'Night Stalker',
        'STR',
        23,
        3,
        110,
        18,
        2.2,
        81.8,
        15,
        1.6,
        61.4,
        295,
        5,
        67,
        150,
        'melee',
        0.6
    ),
    (
        66,
        'Nyx Assassin',
        'AGI',
        17,
        2.5,
        89.5,
        18,
        2.5,
        90.5,
        21,
        2.1,
        81.9,
        310,
        4,
        49,
        150,
        'melee',
        0.6
    ),
    (
        67,
        'Ogre Magi',
        'INT',
        23,
        3.3,
        118.7,
        14,
        1.5,
        57.5,
        15,
        2.5,
        87.5,
        290,
        6.33,
        75,
        150,
        'melee',
        0.6
    ),
    (
        68,
        'Omniknight',
        'STR',
        23,
        3.1,
        112.9,
        15,
        2,
        73,
        16,
        2.1,
        76.9,
        315,
        4.5,
        64,
        150,
        'melee',
        0.6
    ),
    (
        69,
        'Oracle',
        'INT',
        20,
        2.4,
        89.6,
        15,
        1.7,
        64.3,
        26,
        3.8,
        136.2,
        295,
        3.5,
        45,
        620,
        'ranged',
        0.7
    ),
    (
        70,
        'Pangolier',
        'AGI',
        17,
        2.5,
        89.5,
        18,
        3.2,
        110.8,
        16,
        1.9,
        71.1,
        300,
        4,
        57,
        150,
        'melee',
        0.9
    ),
    (
        71,
        'Phantom Assassin',
        'AGI',
        19,
        2,
        77,
        23,
        3.2,
        115.8,
        15,
        1.4,
        55.6,
        305,
        4.83,
        56,
        150,
        'melee',
        0.8
    ),
    (
        72,
        'Phantom Lancer',
        'AGI',
        19,
        2.2,
        82.8,
        26,
        3.2,
        118.8,
        21,
        2,
        79,
        290,
        3.33,
        62,
        150,
        'melee',
        0.6
    ),
    (
        73,
        'Phoenix',
        'STR',
        23,
        3.6,
        127.4,
        12,
        1.5,
        55.5,
        16,
        1.8,
        68.2,
        280,
        1,
        59,
        525,
        'ranged',
        0.9
    ),
    (
        74,
        'Primal Beast',
        'STR',
        26,
        4.3,
        150.7,
        15,
        1,
        44,
        16,
        1.4,
        56.6,
        310,
        4.5,
        64,
        150,
        'melee',
        0.6
    ),
    (
        75,
        'Puck',
        'INT',
        17,
        2.4,
        86.6,
        22,
        2.5,
        94.5,
        23,
        3.5,
        124.5,
        290,
        0.67,
        53,
        550,
        'ranged',
        0.9
    ),
    (
        76,
        'Pudge',
        'STR',
        25,
        3,
        112,
        14,
        1.4,
        54.6,
        16,
        1.8,
        68.2,
        280,
        1.33,
        76,
        175,
        'melee',
        0.7
    ),
    (
        77,
        'Pugna',
        'INT',
        19,
        2,
        77,
        24,
        1.3,
        61.7,
        24,
        5.2,
        174.8,
        330,
        4,
        52,
        630,
        'ranged',
        0.6
    ),
    (
        78,
        'Queen of Pain',
        'INT',
        18,
        2.4,
        87.6,
        22,
        2.5,
        94.5,
        25,
        3.4,
        123.6,
        290,
        3.67,
        55,
        550,
        'ranged',
        0.6
    ),
    (
        79,
        'Razor',
        'AGI',
        22,
        2.8,
        103.2,
        22,
        2.6,
        97.4,
        21,
        2.2,
        84.8,
        290,
        2.67,
        47,
        475,
        'ranged',
        0.6
    ),
    (
        80,
        'Riki',
        'AGI',
        18,
        2.6,
        93.4,
        18,
        1.4,
        58.6,
        14,
        1.3,
        51.7,
        315,
        6,
        63,
        150,
        'melee',
        0.6
    ),
    (
        81,
        'Rubick',
        'INT',
        21,
        2,
        79,
        23,
        2.5,
        95.5,
        25,
        3.1,
        114.9,
        290,
        4.83,
        58,
        550,
        'ranged',
        0.7
    ),
    (
        82,
        'Sand King',
        'STR',
        22,
        2.7,
        100.3,
        19,
        1.8,
        71.2,
        19,
        1.8,
        71.2,
        290,
        3.17,
        55,
        150,
        'melee',
        0.6
    ),
    (
        83,
        'Shadow Demon',
        'INT',
        23,
        2.6,
        98.4,
        18,
        2.2,
        81.8,
        22,
        3.6,
        126.4,
        290,
        3,
        55,
        500,
        'ranged',
        0.6
    ),
    (
        84,
        'Shadow Fiend',
        'AGI',
        19,
        2.7,
        97.3,
        20,
        3.5,
        121.5,
        18,
        2.2,
        81.8,
        305,
        4.33,
        47,
        500,
        'ranged',
        0.9
    ),
    (
        85,
        'Shadow Shaman',
        'INT',
        23,
        2.3,
        89.7,
        16,
        1.6,
        62.4,
        25,
        3.5,
        126.5,
        285,
        4.67,
        72,
        400,
        'ranged',
        0.6
    ),
    (
        86,
        'Silencer',
        'INT',
        19,
        2.2,
        82.8,
        22,
        2.4,
        91.6,
        25,
        2.9,
        109.1,
        290,
        3.67,
        57,
        600,
        'ranged',
        0.6
    ),
    (
        87,
        'Skywrath Mage',
        'INT',
        21,
        2,
        79,
        13,
        0.8,
        36.2,
        25,
        4.1,
        143.9,
        325,
        0.17,
        51,
        625,
        'ranged',
        0.6
    ),
    (
        88,
        'Slark',
        'AGI',
        20,
        1.9,
        75.1,
        21,
        1.5,
        64.5,
        16,
        1.7,
        65.3,
        300,
        3.5,
        61,
        150,
        'melee',
        0.7
    ),
    (
        89,
        'Snapfire',
        'STR',
        20,
        3.5,
        121.5,
        16,
        1.9,
        71.1,
        21,
        2.2,
        84.8,
        300,
        3.67,
        52,
        500,
        'ranged',
        0.6
    ),
    (
        90,
        'Sniper',
        'AGI',
        19,
        2,
        77,
        27,
        3.2,
        119.8,
        15,
        2.6,
        90.4,
        285,
        3.5,
        46,
        550,
        'ranged',
        0.7
    ),
    (
        91,
        'Spectre',
        'AGI',
        23,
        2.5,
        95.5,
        25,
        2.1,
        85.9,
        16,
        1.7,
        65.3,
        290,
        5.17,
        52,
        150,
        'melee',
        0.6
    ),
    (
        92,
        'Spirit Breaker',
        'STR',
        28,
        3,
        115,
        17,
        1.7,
        66.3,
        14,
        1.8,
        66.2,
        295,
        4.83,
        69,
        150,
        'melee',
        0.6
    ),
    (
        93,
        'Storm Spirit',
        'INT',
        21,
        2,
        79,
        22,
        2.6,
        97.4,
        23,
        3.9,
        136.1,
        285,
        4.67,
        57,
        480,
        'ranged',
        0.8
    ),
    (
        94,
        'Sven',
        'STR',
        22,
        3.2,
        114.8,
        21,
        2.2,
        84.8,
        16,
        1.3,
        53.7,
        325,
        3.5,
        65,
        150,
        'melee',
        0.6
    ),
    (
        95,
        'Techies',
        'INT',
        19,
        2.5,
        91.5,
        14,
        1.3,
        51.7,
        25,
        3,
        112,
        300,
        5.33,
        48,
        700,
        'ranged',
        0.6
    ),
    (
        96,
        'Templar Assassin',
        'AGI',
        21,
        2.4,
        90.6,
        23,
        3.2,
        115.8,
        20,
        2,
        78,
        305,
        4.83,
        59,
        160,
        'melee',
        0.7
    ),
    (
        97,
        'Terrorblade',
        'AGI',
        16,
        2,
        74,
        22,
        4,
        138,
        19,
        1.6,
        65.4,
        315,
        8.67,
        58,
        150,
        'melee',
        0.8
    ),
    (
        98,
        'Tidehunter',
        'STR',
        27,
        3.5,
        128.5,
        15,
        1.5,
        58.5,
        18,
        1.7,
        67.3,
        300,
        2.5,
        58,
        150,
        'melee',
        0.6
    ),
    (
        99,
        'Timbersaw',
        'STR',
        25,
        3.5,
        126.5,
        16,
        1.6,
        62.4,
        23,
        2.7,
        101.3,
        290,
        2.67,
        56,
        150,
        'melee',
        0.6
    ),
    (
        100,
        'Tinker',
        'INT',
        19,
        2.5,
        91.5,
        13,
        1.2,
        47.8,
        30,
        3.3,
        125.7,
        290,
        4.17,
        58,
        500,
        'ranged',
        0.6
    ),
    (
        101,
        'Tiny',
        'STR',
        30,
        4,
        146,
        0,
        0,
        0,
        17,
        2.2,
        80.8,
        285,
        0,
        67,
        150,
        'melee',
        0.6
    ),
    (
        102,
        'Treant Protector',
        'STR',
        25,
        3.4,
        123.6,
        15,
        1.8,
        67.2,
        20,
        1.8,
        72.2,
        285,
        1.5,
        95,
        150,
        'melee',
        0.6
    ),
    (
        103,
        'Troll Warlord',
        'AGI',
        21,
        2.5,
        93.5,
        23,
        3.3,
        118.7,
        13,
        1,
        42,
        290,
        2.83,
        58,
        500,
        'ranged',
        0.6
    ),
    (
        104,
        'Tusk',
        'STR',
        23,
        3.9,
        136.1,
        23,
        2.1,
        83.9,
        18,
        1.7,
        67.3,
        310,
        4.83,
        54,
        150,
        'melee',
        0.7
    ),
    (
        105,
        'Underlord',
        'STR',
        25,
        3,
        112,
        12,
        1.6,
        58.4,
        17,
        2.3,
        83.7,
        290,
        5,
        68,
        200,
        'melee',
        0.6
    ),
    (
        106,
        'Undying',
        'STR',
        22,
        2.4,
        91.6,
        10,
        1.2,
        44.8,
        27,
        2.8,
        108.2,
        300,
        2.67,
        65,
        150,
        'melee',
        0.6
    ),
    (
        107,
        'Ursa',
        'AGI',
        25,
        2.6,
        100.4,
        18,
        2.6,
        93.4,
        16,
        1.5,
        59.5,
        310,
        4,
        46,
        150,
        'melee',
        0.6
    ),
    (
        108,
        'Vengeful Spirit',
        'AGI',
        19,
        2.6,
        94.4,
        20,
        3.2,
        112.8,
        19,
        1.5,
        62.5,
        295,
        3.33,
        52,
        400,
        'ranged',
        0.6
    ),
    (
        109,
        'Venomancer',
        'AGI',
        19,
        2.1,
        79.9,
        24,
        2.8,
        105.2,
        19,
        1.8,
        71.2,
        280,
        4,
        49,
        450,
        'ranged',
        0.6
    ),
    (
        110,
        'Viper',
        'AGI',
        21,
        2.4,
        90.6,
        21,
        2.7,
        99.3,
        17,
        2,
        75,
        275,
        1.5,
        50,
        575,
        'ranged',
        0.6
    ),
    (
        111,
        'Visage',
        'INT',
        22,
        2.8,
        103.2,
        11,
        1.3,
        48.7,
        22,
        2.9,
        106.1,
        285,
        0.83,
        55,
        600,
        'ranged',
        0.6
    ),
    (
        112,
        'Void Spirit',
        'INT',
        22,
        2.6,
        97.4,
        19,
        2.2,
        82.8,
        24,
        3.1,
        113.9,
        295,
        2.17,
        58,
        200,
        'melee',
        0.7
    ),
    (
        113,
        'Warlock',
        'INT',
        24,
        3,
        111,
        10,
        1,
        39,
        25,
        3.1,
        114.9,
        300,
        2.67,
        59,
        600,
        'ranged',
        0.6
    ),
    (
        114,
        'Weaver',
        'AGI',
        16,
        2,
        74,
        17,
        3.1,
        106.9,
        20,
        2,
        78,
        275,
        2.83,
        60,
        425,
        'ranged',
        0.6
    ),
    (
        115,
        'Windranger',
        'INT',
        18,
        2.6,
        93.4,
        17,
        1.4,
        57.6,
        18,
        3.6,
        122.4,
        290,
        1.83,
        56,
        600,
        'ranged',
        0.8
    ),
    (
        116,
        'Winter Wyvern',
        'INT',
        22,
        2.5,
        94.5,
        16,
        1.7,
        65.3,
        26,
        3.6,
        130.4,
        285,
        2.67,
        47,
        425,
        'ranged',
        0.6
    ),
    (
        117,
        'Witch Doctor',
        'INT',
        18,
        2.3,
        84.7,
        13,
        1.4,
        53.6,
        22,
        3.3,
        117.7,
        300,
        2.17,
        61,
        550,
        'ranged',
        0.6
    ),
    (
        118,
        'Wraith King',
        'STR',
        22,
        3,
        109,
        16,
        1.7,
        65.3,
        18,
        1.6,
        64.4,
        315,
        1.67,
        62,
        150,
        'melee',
        0.6
    ),
    (
        119,
        'Zeus',
        'INT',
        19,
        2.1,
        79.9,
        11,
        1.2,
        45.8,
        22,
        3.3,
        117.7,
        315,
        3.83,
        63,
        380,
        'ranged',
        0.6
    );
INSERT INTO PLAYER(
        gamer_name,
        player_name,
        player_country,
        player_region,
        player_role,
        team_id,
        player_rank
    )
VALUES (
        'dnm',
        'David Cossio',
        'United States',
        'North America',
        'Carry',
        1,
        1
    ),
    (
        'Speeed',
        'Paul Bocchicchio',
        'United States',
        'North America',
        'Offlaner',
        1,
        265
    ),
    (
        'Kitzz',
        'Francis Arriola',
        'United States',
        'North America',
        'Solo Middle',
        1,
        123
    ),
    (
        'CTOMAHEH1',
        'Nikolay Kalchev',
        'Bulgaria',
        'Europe',
        'Support',
        1,
        145
    ),
    (
        'albinozebra1',
        'Matthew Conley',
        'United States',
        'North America',
        'Support',
        1,
        251
    ),
    (
        'charlie',
        'Charlie Arat',
        'Sweden',
        'Europe',
        'Carry',
        26,
        215
    ),
    (
        'Loda',
        'Jonathan Emanuel Berg',
        'Sweden',
        'Europe',
        'Coach',
        26,
        165
    ),
    (
        's4',
        'Gustav Magnusson',
        'Sweden',
        'Europe',
        'Offlaner',
        26,
        130
    ),
    (
        'ChYuan',
        'Ng Kee Chyuan',
        'Malaysia',
        'Southeast Asia',
        'Solo Middle',
        26,
        37
    ),
    (
        'ponlo',
        'Remus Goh Zhi Xian',
        'Singapore',
        'Southeast Asia',
        'Support',
        26,
        21
    ),
    (
        'Handsken',
        'Simon Rasmus Haag',
        'Sweden',
        'Europe',
        'Support',
        26,
        229
    ),
    (
        'Lumière',
        'Edward Guillen Valencia',
        'Peru',
        'South America',
        'Carry',
        13,
        171
    ),
    (
        'Vitaly',
        'Pablo Cesar Angulo Roman',
        'Peru',
        'South America',
        'Offlaner',
        13,
        363
    ),
    (
        '4nalog',
        'João Gabriel Giannini',
        'Brazil',
        'South America',
        'Solo Middle',
        13,
        141
    ),
    (
        'Thiolicor',
        'Thiago de Oliveira Cordeiro',
        'Brazil',
        'South America',
        'Support',
        13,
        95
    ),
    (
        'Gardick',
        'Brayan Antony López Cárdenas',
        'Peru',
        'South America',
        'Support',
        13,
        246
    ),
    (
        'Rises',
        'Diego Nicolás Ortas Rodríguez',
        'Uruguay',
        'South America',
        'Carry',
        2,
        271
    ),
    (
        'Monster',
        'Steven Noel',
        'United States',
        'North America',
        'Offlaner',
        2,
        368
    ),
    (
        'BlackSoul',
        'Josue Ronald Ticona Aliendre',
        'Bolivia',
        'South America',
        'Solo Middle',
        2,
        69
    ),
    (
        'wij',
        'Nicolás Moreno',
        'Argentina',
        'South America',
        'Support',
        2,
        2
    ),
    (
        'Yadomi',
        'Junior Reyes Rimari',
        'Peru',
        'South America',
        'Support',
        2,
        342
    ),
    (
        'monkeys-forever',
        'Jaron Clinton',
        'United States',
        'North America',
        'Offlaner',
        3,
        259
    ),
    (
        'Xcalibur',
        'Steve Ye',
        'Sweden',
        'Europe',
        'Solo Middle',
        3,
        96
    ),
    (
        'Febby',
        'Kim Yong-min',
        'South Korea',
        'Other',
        'Support',
        3,
        41
    ),
    (
        'Zfreek',
        'Zakari Freedman',
        'United States',
        'North America',
        'Support',
        3,
        206
    ),
    (
        'inYourdreaM',
        'Muhammad Rizky',
        'Indonesia',
        'Southeast Asia',
        'Carry',
        68,
        135
    ),
    (
        'Yowe',
        'Yuri Dave Pacaña',
        'Philippines',
        'Southeast Asia',
        'Carry',
        68,
        29
    ),
    (
        'Clairvoyance',
        'Aaron Kim',
        'Canada',
        'North America',
        'Coach',
        68,
        64
    ),
    (
        'Koala',
        'Farand Kowara',
        'Indonesia',
        'Southeast Asia',
        'Coach',
        68,
        146
    ),
    (
        'db-',
        'Daud Budiawan',
        'Indonesia',
        'Southeast Asia',
        'Offlaner',
        68,
        243
    ),
    (
        'Jhocam',
        'Tri Kuncoro',
        'Indonesia',
        'Southeast Asia',
        'Support',
        68,
        203
    ),
    (
        'Varizh',
        'Rizki Varizh',
        'Indonesia',
        'Southeast Asia',
        'Support',
        68,
        24
    ),
    (
        'Ulu',
        'Wang Jiakai',
        'China',
        'China',
        'Carry',
        55,
        172
    ),
    (
        '86',
        'Chen Yuxuan',
        'China',
        'China',
        'Coach',
        55,
        169
    ),
    (
        'Op',
        'Ou Peng',
        'China',
        'China',
        'Coach',
        55,
        179
    ),
    (
        '生死',
        'Xiao Yihu',
        'China',
        'China',
        'Offlaner',
        55,
        144
    ),
    (
        'White丶Album',
        'Liu Yuhao',
        'China',
        'China',
        'Solo Middle',
        55,
        282
    ),
    (
        'RedPanda',
        'Ru Zhihao',
        'China',
        'China',
        'Support',
        55,
        77
    ),
    (
        'TK',
        'He Boyi',
        'China',
        'China',
        'Support',
        55,
        156
    ),
    (
        'StoneBank',
        'Denis Korzh',
        'Ukraine',
        'Europe',
        'Carry',
        4,
        331
    ),
    (
        'Funn1k',
        'Glib Lipatnikov',
        'Ukraine',
        'Europe',
        'Offlaner',
        4,
        312
    ),
    (
        'Dendi',
        'Danil Ishutin',
        'Ukraine',
        'Europe',
        'Solo Middle',
        4,
        132
    ),
    (
        'MoOz',
        'Joel Mori Ozambela',
        'Peru',
        'South America',
        'Support',
        4,
        22
    ),
    (
        'Lodine',
        'Oleg Kvasha',
        'Ukraine',
        'Europe',
        'Support',
        4,
        134
    ),
    (
        'Ñengo',
        'José Luis Laura',
        'Peru',
        'South America',
        'Solo Middle',
        14,
        221
    ),
    (
        'Dark_Demon',
        'Diego Mathias Huamán',
        'Peru',
        'South America',
        'Support',
        14,
        139
    ),
    (
        'K1',
        'Héctor Antonio Rodríguez',
        'Peru',
        'South America',
        'Carry',
        15,
        92
    ),
    (
        'Raykill',
        'Eduardo Nuñez',
        'Venezuela',
        'South America',
        'Coach',
        15,
        49
    ),
    (
        'Sacred',
        'Rafael Hinostroza Yonatan',
        'Peru',
        'South America',
        'Offlaner',
        15,
        180
    ),
    (
        'Valqui',
        'Thomas Jaulis Romero',
        'Peru',
        'South America',
        'Offlaner',
        15,
        200
    ),
    (
        'DarkMago',
        'Herrera Martínez Oswaldo Gonzalo',
        'Peru',
        'South America',
        'Solo Middle',
        15,
        28
    ),
    (
        'Scofield',
        'Elvis De la Cruz Peña',
        'Peru',
        'South America',
        'Support',
        15,
        344
    ),
    (
        'StingeR',
        'Steven Edwin Vargas Mamani',
        'Peru',
        'South America',
        'Support',
        15,
        305
    ),
    (
        'Pure',
        'Ivan Moskalenko',
        'Russia',
        'Europe',
        'Carry',
        40,
        298
    ),
    (
        'boo1k',
        'Anatoly Ivanov',
        'Russia',
        'Europe',
        'Coach',
        40,
        44
    ),
    (
        'Nightfall',
        'Egor Grigorenko',
        'Russia',
        'Europe',
        'Offlaner',
        40,
        370
    ),
    (
        'gpk',
        'Danil Skutin',
        'Russia',
        'Europe',
        'Solo Middle',
        40,
        335
    ),
    (
        'Save-',
        'Vitalie Melnic',
        'Moldova',
        'Europe',
        'Support',
        40,
        307
    ),
    (
        'TORONTOTOKYO',
        'Alexander Khertek',
        'Russia',
        'Europe',
        'Support',
        40,
        196
    ),
    (
        'Raven',
        'Marc Polo Luis Fausto',
        'Philippines',
        'Southeast Asia',
        'Carry',
        69,
        248
    ),
    (
        'Kuku',
        'Carlo Palad',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        69,
        186
    ),
    (
        'Karl',
        'Karl Matthew Baldovino',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        69,
        46
    ),
    (
        'eyyou',
        'Nico Barcelon',
        'Philippines',
        'Southeast Asia',
        'Support',
        69,
        365
    ),
    (
        'TIMS',
        'Timothy John Randrup',
        'Philippines',
        'Southeast Asia',
        'Support',
        69,
        219
    ),
    (
        'JaCkky',
        'Souliya Khoomphetsavong',
        'Laos',
        'Southeast Asia',
        'Carry',
        70,
        81
    ),
    (
        'Forev',
        'Lee Sang-don',
        'South Korea',
        'Other',
        'Coach',
        70,
        290
    ),
    (
        'Masaros',
        'Natthaphon Ouanphakdee',
        'Thailand',
        'Southeast Asia',
        'Offlaner',
        70,
        147
    ),
    (
        'Kordan',
        'Teng Tjin Yao',
        'Singapore',
        'Southeast Asia',
        'Solo Middle',
        70,
        349
    ),
    (
        'PlayHard',
        'Prieme Ejay Banquil',
        'Philippines',
        'Southeast Asia',
        'Support',
        70,
        193
    ),
    (
        'DuBu',
        'Kim Doo-young',
        'South Korea',
        'Other',
        'Support',
        70,
        213
    ),
    (
        'Natsumi-',
        'John Anthony Vargas',
        'Philippines',
        'Southeast Asia',
        'Carry',
        71,
        93
    ),
    (
        'Mushi',
        'Chai Yee Fung',
        'Malaysia',
        'Southeast Asia',
        'Coach',
        71,
        152
    ),
    (
        'Fbz',
        'Saieful Ilham',
        'Indonesia',
        'Southeast Asia',
        'Offlaner',
        71,
        67
    ),
    (
        'Yopaj',
        'Erin Jasper Ferrer',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        71,
        352
    ),
    (
        'Xepher',
        'Kenny Deo',
        'Indonesia',
        'Southeast Asia',
        'Support',
        71,
        23
    ),
    (
        'xNova',
        'Yap Jian Wei',
        'Malaysia',
        'Southeast Asia',
        'Support',
        71,
        25
    ),
    (
        'alberkaaa',
        'Albert Chernoivanov',
        'Russia',
        'Europe',
        'Carry',
        41,
        5
    ),
    (
        'Fervian',
        'Evgeniy Aksyonov',
        'Russia',
        'Europe',
        'Coach',
        41,
        176
    ),
    (
        'Forcemajor',
        'Maksim Meretskii',
        'Russia',
        'Europe',
        'Support',
        41,
        280
    ),
    (
        'Shad',
        'Indji Lub',
        'Netherlands',
        'Europe',
        'Carry',
        27,
        285
    ),
    (
        'Davai Lama',
        'Cedric Deckmyn',
        'Belgium',
        'Europe',
        'Offlaner',
        27,
        151
    ),
    (
        'Flash',
        'Niamtu Angel',
        'Romania',
        'Europe',
        'Support',
        27,
        157
    ),
    (
        'Alexxo',
        'Aleksandar Diklić',
        'Serbia',
        'Europe',
        'Support',
        27,
        187
    ),
    (
        'Adrian',
        'Adrian Briceño Huancas',
        'Peru',
        'South America',
        'Carry',
        16,
        11
    ),
    (
        'Cucahook',
        'José Antonio Espinoza Poccori',
        'Peru',
        'South America',
        'Carry',
        16,
        100
    ),
    (
        'Drakeel',
        'Isaac Zavaleta',
        'Peru',
        'South America',
        'Offlaner',
        16,
        322
    ),
    (
        'Jeimari',
        'Jeremy Ruiz Aguinaga',
        'Peru',
        'South America',
        'Solo Middle',
        16,
        337
    ),
    (
        'Zxca',
        'Amilkar Fhelipe Layme Bonifacio',
        'Peru',
        'South America',
        'Support',
        16,
        33
    ),
    (
        '圣子华炼',
        'Zhong Liushua',
        'China',
        'China',
        'Carry',
        56,
        364
    ),
    (
        'mks',
        'Wong Sim An',
        'Malaysia',
        'Southeast Asia',
        'Carry',
        56,
        114
    ),
    (
        'X1aOyU',
        'Lee Qian Yu',
        'Malaysia',
        'Southeast Asia',
        'Offlaner',
        56,
        164
    ),
    (
        'yChen',
        'Pan Shuaifang',
        'China',
        'China',
        'Solo Middle',
        56,
        63
    ),
    (
        'Lww',
        'Liu Weiwei',
        'China',
        'China',
        'Support',
        56,
        110
    ),
    (
        'Salad',
        'Tang Xiaolei',
        'China',
        'China',
        'Support',
        56,
        296
    ),
    (
        'watson',
        'Alimzhan Islambekov',
        'Kazakhstan',
        'Europe',
        'Carry',
        28,
        350
    ),
    (
        'MeTTpuM',
        'Daniil Gilev',
        'Russia',
        'Europe',
        'Coach',
        28,
        8
    ),
    (
        'Tobi',
        'Tobias Buchner',
        'Austria',
        'Europe',
        'Offlaner',
        28,
        185
    ),
    (
        'Stormstormer',
        'Daniel Schoetzau',
        'Germany',
        'Europe',
        'Solo Middle',
        28,
        16
    ),
    (
        'Fishman',
        'Dzmitry Palishchuk',
        'Belarus',
        'Europe',
        'Support',
        28,
        244
    ),
    (
        'Kataomi`',
        'Vladislav Semenov',
        'Russia',
        'Europe',
        'Support',
        28,
        332
    ),
    (
        'Pakazs',
        'Crhistian Antony Savina Casanova',
        'Peru',
        'South America',
        'Carry',
        17,
        208
    ),
    (
        'Vintage',
        'Juan David Angulo Nicho',
        'Peru',
        'South America',
        'Coach',
        17,
        42
    ),
    (
        'Wisper',
        'Adrián Céspedes Dobles',
        'Bolivia',
        'South America',
        'Offlaner',
        17,
        66
    ),
    (
        'Chris Luck',
        'Jean Pierre Gonzales Salazar',
        'Peru',
        'South America',
        'Solo Middle',
        17,
        160
    ),
    (
        'Matthew',
        'Farith Jeafehe Puente Huamancaja',
        'Peru',
        'South America',
        'Support',
        17,
        309
    ),
    (
        'Pandaboo',
        'Jose Leonardo Padilla Hernandez',
        'Peru',
        'South America',
        'Support',
        17,
        279
    ),
    (
        'Palos',
        'Jinn Marrey P. Lamatao',
        'Philippines',
        'Southeast Asia',
        'Carry',
        72,
        101
    ),
    (
        'Kim0',
        'Kimuel Borromeo Rodis',
        'Philippines',
        'Southeast Asia',
        'Coach',
        72,
        270
    ),
    (
        'March',
        'Park Tae-won',
        'South Korea',
        'Other',
        'Coach',
        72,
        289
    ),
    (
        'Tino',
        'Justine Ryan Evangelista Grimaldo',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        72,
        247
    ),
    (
        'Bob',
        'Mark Anthony A. Urbina',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        72,
        311
    ),
    (
        'BDz',
        'Juan Carlo Chua Manalo',
        'Philippines',
        'Southeast Asia',
        'Support',
        72,
        54
    ),
    (
        'Shanks',
        'Mark Jubert Redira',
        'Philippines',
        'Southeast Asia',
        'Support',
        72,
        71
    ),
    (
        'Berna',
        'Bernardo David Rocca Alarcón',
        'Peru',
        'South America',
        'Carry',
        5,
        225
    ),
    (
        'Fayde',
        'Victor Zuev',
        'United States',
        'North America',
        'Offlaner',
        5,
        273
    ),
    (
        'solji;,',
        'Boris Khundziya',
        'Russia',
        'Europe',
        'Solo Middle',
        5,
        325
    ),
    (
        'Chen',
        'Chen Yi',
        'United States',
        'North America',
        'Support',
        5,
        369
    ),
    (
        'Shoe',
        'Mykyta Zagrebin',
        'United States',
        'North America',
        'Support',
        5,
        48
    ),
    (
        'Gabbi',
        'Kim Villafuerte Santos',
        'Philippines',
        'Southeast Asia',
        'Carry',
        73,
        375
    ),
    (
        'kpii',
        'Damien Chok Sau-jing',
        'Australia',
        'Other',
        'Offlaner',
        73,
        272
    ),
    (
        'Armel',
        'Armel Paul Luna Tabios',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        73,
        205
    ),
    (
        'DJ',
        'Djardel Jicko B. Mampusti',
        'Philippines',
        'Southeast Asia',
        'Support',
        73,
        65
    ),
    (
        'Jaunuel',
        'Jaunuel Arcilla',
        'Philippines',
        'Southeast Asia',
        'Support',
        73,
        162
    ),
    (
        'dyrachyo',
        'Anton Shkredov',
        'Russia',
        'Europe',
        'Carry',
        29,
        264
    ),
    (
        'Ace',
        'Marcus Folke Hoelgaard Christensen',
        'Denmark',
        'Europe',
        'Offlaner',
        29,
        356
    ),
    (
        'Quinn',
        'Quinn Callahan',
        'United States',
        'North America',
        'Solo Middle',
        29,
        283
    ),
    (
        'tOfu',
        'Erik Engel',
        'Germany',
        'Europe',
        'Support',
        29,
        210
    ),
    (
        'Seleri',
        'Melchior Hillenkamp',
        'Netherlands',
        'Europe',
        'Support',
        29,
        304
    ),
    (
        'skem',
        'Rolen Andrei Gabriel Ong',
        'Philippines',
        'Southeast Asia',
        'Carry',
        74,
        12
    ),
    (
        'Force',
        'Nikko Bilocura',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        74,
        281
    ),
    (
        'Kokz',
        'Joshua H. Maraño',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        74,
        336
    ),
    (
        'Roddgeee',
        'Roger Tan Boon Thye',
        'Malaysia',
        'Southeast Asia',
        'Support',
        74,
        214
    ),
    (
        'NARMAN',
        'Ravdan Narmandakh',
        'Mongolia',
        'Other',
        'Support',
        74,
        292
    ),
    (
        'Daxak',
        'Nikita Kuzmin',
        'Russia',
        'Europe',
        'Carry',
        42,
        107
    ),
    (
        'MieRo`',
        'Matvey Vasyunin',
        'Russia',
        'Europe',
        'Offlaner',
        42,
        72
    ),
    (
        'depressed kid',
        'Gleb Zyryanov',
        'Russia',
        'Europe',
        'Solo Middle',
        42,
        53
    ),
    (
        'Antares',
        'Vladislav Kertman',
        'Russia',
        'Europe',
        'Support',
        42,
        60
    ),
    (
        'Solo',
        'Alexey Berezin',
        'Russia',
        'Europe',
        'Support',
        42,
        358
    ),
    (
        'dream`',
        'Kıyalbek Tayirov',
        'Kyrgyzstan',
        'CIS',
        'Carry',
        43,
        328
    ),
    (
        'TheHeartlessKing',
        'Maxim Fadeev',
        'Ukraine',
        'Europe',
        'Coach',
        43,
        355
    ),
    (
        'Cloud',
        'Alexander Zakharov',
        'Russia',
        'Europe',
        'Offlaner',
        43,
        339
    ),
    (
        'Worick',
        'Vitalij Brezgin',
        'Russia',
        'Europe',
        'Solo Middle',
        43,
        263
    ),
    (
        'HappyDyurara',
        'Sergey Horonzhiy',
        'Belarus',
        'Europe',
        'Support',
        43,
        133
    ),
    (
        'doodle',
        'Lin Zikai',
        'China',
        'China',
        'Carry',
        57,
        267
    ),
    (
        'ButterflyEffect',
        'Ni Weijie',
        'China',
        'China',
        'Solo Middle',
        57,
        223
    ),
    (
        'Summer',
        'Tang Kaiwen',
        'China',
        'China',
        'Solo Middle',
        57,
        233
    ),
    (
        'sj',
        'Wang Sijie',
        'China',
        'China',
        'Support',
        57,
        302
    ),
    (
        'Mnz',
        'Alonso León',
        'Peru',
        'South America',
        'Carry',
        18,
        166
    ),
    (
        'FalcoStyle',
        'Huester Valenzuela',
        'Peru',
        'South America',
        'Coach',
        18,
        346
    ),
    (
        'Oscar',
        'Oscar David Chavez Jimenez',
        'Bolivia',
        'South America',
        'Offlaner',
        18,
        7
    ),
    (
        'SLATEM$',
        'Jordan Pascasio Vega',
        'Peru',
        'South America',
        'Solo Middle',
        18,
        170
    ),
    (
        'sl4d1n-',
        'Alexis Cepeda Sitl Sitl',
        'Ecuador',
        'South America',
        'Support',
        18,
        293
    ),
    (
        'Mjz',
        'Romel Quinteros',
        'Peru',
        'South America',
        'Support',
        18,
        177
    ),
    (
        'Papita',
        'Mariano Caneda',
        'Argentina',
        'South America',
        'Coach',
        19,
        374
    ),
    (
        'Frank',
        'Frank Alberto Arias Ayala',
        'Peru',
        'South America',
        'Offlaner',
        19,
        250
    ),
    (
        'Leostyle-',
        'Leonardo Sifuentes',
        'Peru',
        'South America',
        'Solo Middle',
        19,
        207
    ),
    (
        'Genek',
        'Moises Asencios Santillan',
        'Peru',
        'South America',
        'Support',
        19,
        43
    ),
    (
        'Prada',
        'Sergio Toribio Orihuela',
        'Peru',
        'South America',
        'Support',
        19,
        68
    ),
    (
        'Otaker',
        'Roman Aliullov',
        'Non-representing',
        'Other',
        'Carry',
        30,
        287
    ),
    (
        'MiLAN',
        'Milan Kozomara',
        'Bosnia and Herzegovina',
        'Europe',
        'Coach',
        30,
        189
    ),
    (
        'Rajjix',
        'Roy al Rajji',
        'Lebanon',
        'Other',
        'Offlaner',
        30,
        91
    ),
    (
        'Xibbe',
        'Andreas Ragnemalm',
        'Sweden',
        'Europe',
        'Offlaner',
        30,
        88
    ),
    (
        'Supream^',
        'Ondřej Štarha',
        'Czechia',
        'Other',
        'Solo Middle',
        30,
        184
    ),
    (
        'Immersion',
        'Aleksandr Khmelevskoi',
        'Russia',
        'Europe',
        'Support',
        30,
        112
    ),
    (
        'Kidaro',
        'Ivan Bondarev',
        'Ukraine',
        'Europe',
        'Support',
        30,
        220
    ),
    (
        'Emo',
        'Zhou Yi',
        'China',
        'China',
        'Carry',
        58,
        84
    ),
    (
        'super',
        'Su Peng',
        'China',
        'China',
        'Coach',
        58,
        174
    ),
    (
        'Irving',
        'Li Jian',
        'China',
        'China',
        'Offlaner',
        58,
        306
    ),
    (
        'Dust',
        'Zhou Shiyuan',
        'China',
        'China',
        'Solo Middle',
        58,
        97
    ),
    (
        'qyqx',
        'Cui Chenyang',
        'China',
        'China',
        'Support',
        58,
        61
    ),
    (
        'poloson',
        'Wilson Koh Chin Wei',
        'Singapore',
        'Southeast Asia',
        'Support',
        58,
        278
    ),
    (
        'pio65',
        'Alexandr Zalivako',
        'Belarus',
        'Europe',
        'Carry',
        31,
        242
    ),
    (
        'OwnedMe',
        'Mathias Huynh',
        'Denmark',
        'Europe',
        'Offlaner',
        31,
        131
    ),
    (
        'Mo13ei',
        'Fabian Knehr',
        'Germany',
        'Europe',
        'Solo Middle',
        31,
        45
    ),
    (
        'jmn',
        'Jonas Vincent Matz',
        'Germany',
        'Europe',
        'Support',
        31,
        262
    ),
    (
        'Qupe',
        'Jan Tinnemeier',
        'Germany',
        'Europe',
        'Support',
        31,
        275
    ),
    (
        'Costabile',
        'Guilherme Silva Costábile',
        'Brazil',
        'South America',
        'Carry',
        20,
        113
    ),
    (
        'DFlash',
        'Bruno de Souza Oliveira',
        'Brazil',
        'South America',
        'Coach',
        20,
        78
    ),
    (
        'tavo',
        'Otávio Gabriel Cerqueira Silva',
        'Brazil',
        'South America',
        'Offlaner',
        20,
        216
    ),
    (
        '4dr',
        'Adriano de Paula Machado',
        'Brazil',
        'South America',
        'Solo Middle',
        20,
        36
    ),
    (
        'Kingrd',
        'Danylo Nascimento',
        'Brazil',
        'South America',
        'Support',
        20,
        149
    ),
    (
        'KJ',
        'Matheus Santos Jungles Diniz',
        'Brazil',
        'South America',
        'Support',
        20,
        317
    ),
    (
        'eGo',
        'Luo Bin',
        'China',
        'China',
        'Carry',
        59,
        47
    ),
    (
        'Flyby',
        'Su Lei',
        'China',
        'China',
        'Offlaner',
        59,
        85
    ),
    (
        'AlaCrity',
        'Vincent Hiew Teck Yoong',
        'Malaysia',
        'Southeast Asia',
        'Solo Middle',
        59,
        182
    ),
    (
        'XCJ',
        'Xiao Chaojian',
        'China',
        'China',
        'Support',
        59,
        297
    ),
    (
        'FelixCiaoBa',
        'Chong Wei Lun',
        'Malaysia',
        'Southeast Asia',
        'Support',
        59,
        102
    ),
    (
        'Fonte',
        'Lai Xingyu',
        'China',
        'China',
        'Carry',
        60,
        347
    ),
    (
        'Tzy丶',
        'Jiang Bo',
        'China',
        'China',
        'Offlaner',
        60,
        321
    ),
    (
        'pp',
        'Jin Peng',
        'China',
        'China',
        'Solo Middle',
        60,
        154
    ),
    (
        'guoguo',
        'Zhan Yaoyang',
        'China',
        'China',
        'Support',
        60,
        269
    ),
    (
        'Yp',
        'Yang Yuepeng',
        'China',
        'China',
        'Support',
        60,
        150
    ),
    (
        'lowskill',
        'Tamás Kaszás',
        'Hungary',
        'Europe',
        'Carry',
        32,
        190
    ),
    (
        'BoraNija',
        'Duško Boranijašević',
        'Serbia',
        'Europe',
        'Solo Middle',
        32,
        212
    ),
    (
        'Velheor',
        'Fedor Rusihin',
        'Russia',
        'Europe',
        'Support',
        32,
        199
    ),
    (
        'eleven',
        'Munkh-Erdene Battsooj',
        'Mongolia',
        'Other',
        'Offlaner',
        75,
        140
    ),
    (
        '423',
        'Altanginj Bilguun',
        'Mongolia',
        'Other',
        'Solo Middle',
        75,
        357
    ),
    (
        'Ace12',
        'Batbayasgalan Narankhand',
        'Mongolia',
        'Other',
        'Support',
        75,
        300
    ),
    (
        'RedMonster',
        'Jhon Albert Mamani',
        'Peru',
        'South America',
        'Coach',
        22,
        226
    ),
    (
        'ArzenT',
        'Juan Antonio Arteaga Beltran',
        'Peru',
        'South America',
        'Offlaner',
        22,
        329
    ),
    (
        'JachiTo',
        'Luis Lanazca',
        'Peru',
        'South America',
        'Solo Middle',
        22,
        58
    ),
    (
        'Smoker',
        'Pablo Yarlequè',
        'Peru',
        'South America',
        'Support',
        22,
        360
    ),
    (
        'BarabaNN',
        'Sergey Posvyashchenniy',
        'Russia',
        'Europe',
        'Carry',
        44,
        27
    ),
    (
        'Gatciy',
        'Azamat Gatciev',
        'Russia',
        'Europe',
        'Support',
        44,
        105
    ),
    (
        'fn',
        'Rostislav Lozovoi',
        'Ukraine',
        'Europe',
        'Solo Middle',
        46,
        76
    ),
    (
        'Nande',
        'Lasha Narsia',
        'Georgia',
        'Europe',
        'Carry',
        33,
        143
    ),
    (
        'SkyLark',
        'Kharis Zafeiriou',
        'Greece',
        'Europe',
        'Offlaner',
        33,
        230
    ),
    (
        'grizine',
        'Nenad Lukic',
        'Serbia',
        'Europe',
        'Offlaner',
        33,
        163
    ),
    (
        'W1sh-',
        'Irakli Peranidze',
        'Georgia',
        'Europe',
        'Solo Middle',
        33,
        341
    ),
    (
        'dEsire',
        'Sakis Kartsampas',
        'Greece',
        'Europe',
        'Support',
        33,
        191
    ),
    (
        'SsaSpartan',
        'Giorgos Giannakopoulos',
        'Greece',
        'Europe',
        'Support',
        33,
        155
    ),
    (
        'V-Tune',
        'Alik Vorobey',
        'Ukraine',
        'Europe',
        'Carry',
        47,
        324
    ),
    (
        'Artstyle',
        'Ivan Antonov',
        'Ukraine',
        'Europe',
        'Coach',
        47,
        52
    ),
    (
        'laise',
        'Vladislav Lais',
        'Ukraine',
        'Europe',
        'Offlaner',
        47,
        122
    ),
    (
        'Nicky`Cool',
        'Nikita Ostakhov',
        'Kazakhstan',
        'Europe',
        'Solo Middle',
        47,
        62
    ),
    (
        'Malady',
        'Arman Orazbayev',
        'Kazakhstan',
        'Europe',
        'Support',
        47,
        142
    ),
    (
        'swedenstrong',
        'Georgii Zainalabidov',
        'Non-representing',
        'Other',
        'Support',
        47,
        258
    ),
    (
        'Kiritych',
        'Ilya Ulyanov',
        'Russia',
        'Europe',
        'Carry',
        48,
        338
    ),
    (
        'j4',
        'Alexei Lipai',
        'Belarus',
        'Europe',
        'Coach',
        48,
        315
    ),
    (
        'Vazya',
        'Ivan German',
        'Russia',
        'Europe',
        'Offlaner',
        48,
        31
    ),
    (
        'Malr1ne',
        'Stanislav Potorak',
        'Russia',
        'Europe',
        'Solo Middle',
        48,
        238
    ),
    (
        'Hellscream',
        'Kirill Lagutik',
        'Belarus',
        'Europe',
        'Support',
        48,
        218
    ),
    (
        'so bad',
        'Vitaly Oshmankevich',
        'Belarus',
        'Europe',
        'Support',
        48,
        115
    ),
    (
        'ChuaN',
        'Wong Hock Chuan',
        'Malaysia',
        'Southeast Asia',
        'Coach',
        76,
        354
    ),
    (
        'Enryu',
        'Michael Roi T. Ladines',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        76,
        109
    ),
    (
        'Ken',
        'Argle Ken C. Llesis',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        76,
        340
    ),
    (
        'ATF',
        'Ammar Al-Assaf',
        'Jordan',
        'Other',
        'Carry',
        34,
        30
    ),
    (
        'Miracle-',
        'Amer Al-Barkawi',
        'Jordan',
        'Other',
        'Carry',
        34,
        153
    ),
    (
        'ImmortalFaith',
        'Daniel Moza',
        'Romania',
        'Europe',
        'Coach',
        34,
        10
    ),
    (
        'MinD_ContRoL',
        'Ivan Borislavov Ivanov',
        'Bulgaria',
        'Europe',
        'Offlaner',
        34,
        119
    ),
    (
        'SumaiL',
        'Syed Sumail Hassan',
        'Pakistan',
        'Other',
        'Solo Middle',
        34,
        316
    ),
    (
        'Attacker',
        'Mohammed Almheiri',
        'United Arab Emirates',
        'Other',
        'Solo Middle',
        34,
        158
    ),
    (
        'KuroKy',
        'Kuro Salehi Takhasomi',
        'Germany',
        'Europe',
        'Support',
        34,
        3
    ),
    (
        'GH',
        'Maroun Merhej',
        'Lebanon',
        'Other',
        'Support',
        34,
        128
    ),
    (
        'Yamsun',
        'Luke Wang',
        'United States',
        'North America',
        'Carry',
        6,
        74
    ),
    (
        'Moo',
        'David William Hull',
        'United States',
        'North America',
        'Offlaner',
        6,
        125
    ),
    (
        'Gunnar',
        'Nicolas Lopez',
        'United States',
        'North America',
        'Solo Middle',
        6,
        13
    ),
    (
        'LESLÃO',
        'Rodrigo Lelis Santos',
        'Brazil',
        'South America',
        'Support',
        6,
        237
    ),
    (
        'Husky',
        'Jacob Fifik',
        'United States',
        'North America',
        'Support',
        6,
        376
    ),
    (
        'Yuragi',
        'Artem Golubiev',
        'Ukraine',
        'Europe',
        'Carry',
        35,
        86
    ),
    (
        'Chuvash',
        'Evgenii Makarov',
        'Non-representing',
        'Other',
        'Coach',
        35,
        161
    ),
    (
        'DM',
        'Dmitry Dorokhin',
        'Russia',
        'Europe',
        'Offlaner',
        35,
        204
    ),
    (
        'bzm',
        'Bozhidar Bogdanov',
        'Bulgaria',
        'Europe',
        'Solo Middle',
        35,
        314
    ),
    (
        'Taiga',
        'Tommy Le',
        'Norway',
        'Europe',
        'Support',
        35,
        124
    ),
    (
        'Misha',
        'Mikhail Agatov',
        'Russia',
        'Europe',
        'Support',
        35,
        255
    ),
    (
        'Munkushi~',
        'Nikita Chepurnykh',
        'Russia',
        'Europe',
        'Carry',
        49,
        326
    ),
    (
        'G',
        'Sergei Bragin',
        'Russia',
        'Europe',
        'Coach',
        49,
        103
    ),
    (
        'AfterLife',
        'Vasilii Shishkin',
        'Russia',
        'Europe',
        'Offlaner',
        49,
        217
    ),
    (
        'Ainkrad',
        'Aleksey Diveevskiy',
        'Belarus',
        'Europe',
        'Solo Middle',
        49,
        202
    ),
    (
        'pantomem',
        'Nikita Balaganin',
        'Belarus',
        'Europe',
        'Support',
        49,
        116
    ),
    (
        'Gilgir',
        'Geogrii Svistunov',
        'Russia',
        'Europe',
        'Support',
        49,
        183
    ),
    (
        'Bok',
        'Jun B. Kanehara',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        77,
        234
    ),
    (
        'Mac',
        'Mc Nicholson Villanueva',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        77,
        148
    ),
    (
        'cml',
        'Bryle Jacob D. Alvizo',
        'Philippines',
        'Southeast Asia',
        'Support',
        77,
        159
    ),
    (
        'Jing',
        'John Rey Yee Duyan',
        'Philippines',
        'Southeast Asia',
        'Support',
        77,
        50
    ),
    (
        'Ame',
        'Wang Chunyu',
        'China',
        'China',
        'Carry',
        61,
        253
    ),
    (
        'shiro',
        'Guo Xuanang',
        'China',
        'China',
        'Carry',
        61,
        178
    ),
    (
        'xiao8',
        'Zhang Ning',
        'China',
        'China',
        'Coach',
        61,
        99
    ),
    (
        '项羽',
        'Li Longwu',
        'China',
        'China',
        'Offlaner',
        61,
        121
    ),
    (
        'NothingToSay',
        'Cheng Jin Xiang',
        'Malaysia',
        'Southeast Asia',
        'Solo Middle',
        61,
        198
    ),
    (
        'planet',
        'Lin Hao',
        'China',
        'China',
        'Support',
        61,
        173
    ),
    (
        'y`',
        'Zhang Yiping',
        'China',
        'China',
        'Support',
        61,
        366
    ),
    (
        'shigetsu',
        'Maxim Popadinec',
        'Ukraine',
        'Europe',
        'Carry',
        51,
        127
    ),
    (
        'Malik',
        'Abdimalik Sailau',
        'Kazakhstan',
        'Europe',
        'Offlaner',
        51,
        117
    ),
    (
        'young G',
        'Nikita Bochko',
        'Belarus',
        'Europe',
        'Solo Middle',
        51,
        4
    ),
    (
        'Danial',
        'Danial Alibaev',
        'Kazakhstan',
        'Europe',
        'Support',
        51,
        19
    ),
    (
        'Hduo',
        'Ilya Deriglazov',
        'Ukraine',
        'Europe',
        'Support',
        51,
        286
    ),
    (
        'Benjaz',
        'Benjamín Lanao Barrios',
        'Peru',
        'South America',
        'Offlaner',
        23,
        310
    ),
    (
        'Cara',
        'Alejandro Guzmán Mendoza',
        'Peru',
        'South America',
        'Offlaner',
        23,
        108
    ),
    (
        'PiPi',
        'Jeanpierre Valente Arroyo',
        'Peru',
        'South America',
        'Solo Middle',
        23,
        351
    ),
    (
        'Super',
        'Xie Junhao',
        'China',
        'China',
        'Coach',
        62,
        222
    ),
    (
        'Chalice',
        'Yang Shenyi',
        'China',
        'China',
        'Offlaner',
        62,
        40
    ),
    (
        'Somnus',
        'Lu Yao',
        'China',
        'China',
        'Solo Middle',
        62,
        9
    ),
    (
        'kaka',
        'Hu Liangzhi',
        'China',
        'China',
        'Support',
        62,
        17
    ),
    (
        'Arteezy',
        'Artour Babaev',
        'Canada',
        'North America',
        'Carry',
        7,
        211
    ),
    (
        'BuLba',
        'Kanishka Sosale',
        'United States',
        'North America',
        'Coach',
        7,
        308
    ),
    (
        'SabeRLight-',
        'Jonáš Volek',
        'Czechia',
        'Other',
        'Offlaner',
        7,
        323
    ),
    (
        'Abed',
        'Abed Azel L. Yusop',
        'Philippines',
        'Southeast Asia',
        'Solo Middle',
        7,
        197
    ),
    (
        'Cr1t-',
        'Andreas Franck Nielsen',
        'Denmark',
        'Europe',
        'Support',
        7,
        129
    ),
    (
        'Fly',
        'Tal Aizik',
        'Israel',
        'Other',
        'Support',
        7,
        299
    ),
    (
        '23savage',
        'Nuengnara Teeramahanon',
        'Thailand',
        'Southeast Asia',
        'Carry',
        78,
        252
    ),
    (
        'SunBhie',
        'Lee Jeong-jae',
        'South Korea',
        'Other',
        'Coach',
        78,
        14
    ),
    (
        'Jabz',
        'Anucha Jirawong',
        'Thailand',
        'Southeast Asia',
        'Offlaner',
        78,
        15
    ),
    (
        'Mikoto',
        'Rafli Fathur Rahman',
        'Indonesia',
        'Southeast Asia',
        'Solo Middle',
        78,
        87
    ),
    (
        'Oli',
        'Chan Chon Kien',
        'Malaysia',
        'Southeast Asia',
        'Support',
        78,
        175
    ),
    (
        'Q',
        'Worawit Mekchai',
        'Thailand',
        'Southeast Asia',
        'Support',
        78,
        345
    ),
    (
        'Monet',
        'Du Peng',
        'China',
        'China',
        'Carry',
        64,
        73
    ),
    (
        'rOtK',
        'Bai Fan',
        'China',
        'China',
        'Coach',
        64,
        371
    ),
    (
        'Xxs',
        'Lin Jing',
        'China',
        'China',
        'Offlaner',
        64,
        274
    ),
    (
        '一',
        'Zhai Jingkai',
        'China',
        'China',
        'Solo Middle',
        64,
        288
    ),
    (
        'BoBoKa',
        'Ye Zhibiao',
        'China',
        'China',
        'Support',
        64,
        303
    ),
    (
        '皮球',
        'Yu Yajun',
        'China',
        'China',
        'Support',
        64,
        194
    ),
    (
        'Gorgc',
        'Janne Stefanovski',
        'Sweden',
        'Europe',
        'Carry',
        36,
        89
    ),
    (
        'w33',
        'Aliwi Omar',
        'Romania',
        'Europe',
        'Solo Middle',
        36,
        111
    ),
    (
        'Bengan',
        'Jonathan Hansson',
        'Sweden',
        'Europe',
        'Support',
        36,
        79
    ),
    (
        'Pablo',
        'Axel Källman',
        'Sweden',
        'Europe',
        'Support',
        36,
        6
    ),
    (
        'Yuma',
        'Yuma Langlet',
        'Nicaragua',
        'Other',
        'Carry',
        8,
        319
    ),
    (
        'yarin',
        'Yarin Lugassi',
        'Israel',
        'Other',
        'Support',
        8,
        83
    ),
    (
        'Bloody Nine',
        'Daniel Foster',
        'United States',
        'North America',
        'Support',
        8,
        201
    ),
    (
        'fozzy',
        'Adel Zinnatullin',
        'Russia',
        'Europe',
        'Solo Middle',
        53,
        70
    ),
    (
        'Qojqva',
        'Maximilian Bröcker',
        'Germany',
        'Europe',
        'Carry',
        37,
        120
    ),
    (
        'miCKe',
        'Michael Vu',
        'Sweden',
        'Europe',
        'Carry',
        37,
        240
    ),
    (
        'zai',
        'Ludwig Eric Wåhlberg',
        'Sweden',
        'Europe',
        'Offlaner',
        37,
        227
    ),
    (
        'Nisha',
        'Michał Jankowski',
        'Poland',
        'Europe',
        'Solo Middle',
        37,
        167
    ),
    (
        'Jabbz',
        'Mathis Friesel',
        'Germany',
        'Europe',
        'Support',
        37,
        359
    ),
    (
        'Boxi',
        'Samuel Svahn',
        'Sweden',
        'Europe',
        'Support',
        37,
        239
    ),
    (
        'iNSaNiA',
        'Aydin Sarkohi',
        'Sweden',
        'Europe',
        'Support',
        37,
        32
    ),
    (
        'Crystallis',
        'Remco Arets',
        'Netherlands',
        'Europe',
        'Carry',
        38,
        232
    ),
    (
        'Heen',
        'Lee Seung Gon',
        'South Korea',
        'Other',
        'Coach',
        38,
        257
    ),
    (
        'Resolut1on',
        'Roman Fomynok',
        'Ukraine',
        'Europe',
        'Offlaner',
        38,
        343
    ),
    (
        'BOOM',
        'Miroslav Bičan',
        'Czechia',
        'Other',
        'Solo Middle',
        38,
        98
    ),
    (
        'Puppey',
        'Clement Ivanov',
        'Estonia',
        'Europe',
        'Support',
        38,
        266
    ),
    (
        'YapzOr',
        'Yazied Jaradat',
        'Jordan',
        'Other',
        'Support',
        38,
        138
    ),
    (
        'Zayac',
        'Baqyt Emiljanov',
        'Kyrgyzstan',
        'CIS',
        'Support',
        38,
        209
    ),
    (
        'CDR',
        'Lee Jia He',
        'Malaysia',
        'Southeast Asia',
        'Carry',
        79,
        276
    ),
    (
        'ALWAYSWANNAFLY',
        'Andrii Bondarenko',
        'Ukraine',
        'Europe',
        'Coach',
        79,
        353
    ),
    (
        'MidOne',
        'Yeik Nai Zheng',
        'Malaysia',
        'Southeast Asia',
        'Offlaner',
        79,
        168
    ),
    (
        'Raging Potato',
        'Ryan Jay Qui',
        'Philippines',
        'Southeast Asia',
        'Offlaner',
        79,
        82
    ),
    (
        'Moon',
        'Kam Boon Seng',
        'Malaysia',
        'Southeast Asia',
        'Solo Middle',
        79,
        34
    ),
    (
        'ah fu',
        'Tue Soon Chuan',
        'Malaysia',
        'Southeast Asia',
        'Support',
        79,
        136
    ),
    (
        'Boomy',
        'Marvin Salvador Gilos Rushton',
        'Philippines',
        'Southeast Asia',
        'Support',
        79,
        236
    ),
    (
        'Scourge McDuck',
        'Griffin Pappert',
        'United States',
        'North America',
        'Carry',
        9,
        106
    ),
    (
        'high_shaggy',
        'Muhammad Saad Ali Ghaznavi',
        'Canada',
        'North America',
        'Solo Middle',
        9,
        20
    ),
    (
        'empyreaN',
        'Ankit Aggarwal',
        'United States',
        'North America',
        'Support',
        9,
        277
    ),
    (
        'Save',
        'Joseph Jacobson',
        'United States',
        'North America',
        'Support',
        9,
        249
    ),
    (
        'layme',
        'Timur Magomedov',
        'Russia',
        'Europe',
        'Carry',
        10,
        362
    ),
    (
        'esK',
        'Jose Esau Perez Coronel',
        'Mexico',
        'Other',
        'Solo Middle',
        10,
        334
    ),
    (
        'antoha',
        'Anton Marchenko',
        'Non-representing',
        'Other',
        'Support',
        10,
        313
    ),
    (
        'Smiling Knight',
        'Aliaksei Svirydau',
        'Belarus',
        'Europe',
        'Carry',
        24,
        26
    ),
    (
        'LittleBoy',
        'Mario Romero Valdivia',
        'Peru',
        'South America',
        'Offlaner',
        24,
        57
    ),
    (
        'Alone',
        'Ricardo Ernesto Sanchez Fernandez',
        'Peru',
        'South America',
        'Solo Middle',
        24,
        295
    ),
    (
        'Michael-',
        'Miguel Angel Choque Gomez',
        'Bolivia',
        'South America',
        'Support',
        24,
        90
    ),
    (
        'Accel',
        'Cristian Neto Cruz Quispe',
        'Peru',
        'South America',
        'Support',
        24,
        327
    ),
    (
        'Timado',
        'Enzo Gianoli O''Connor',
        'Peru',
        'South America',
        'Carry',
        11,
        104
    ),
    (
        'MoonMeander',
        'David Tan Boon Yang',
        'Canada',
        'North America',
        'Coach',
        11,
        192
    ),
    (
        'kasane',
        'Ilyas Gainullin',
        'Russia',
        'Europe',
        'Offlaner',
        11,
        80
    ),
    (
        'Bryle',
        'Jonathan Bryle Santos De Guia',
        'Canada',
        'North America',
        'Solo Middle',
        11,
        75
    ),
    (
        'Whitemon',
        'Matthew Filemon',
        'Indonesia',
        'Southeast Asia',
        'Support',
        11,
        318
    ),
    (
        'Ari',
        'Matthew Walker',
        'United Kingdom',
        'Europe',
        'Support',
        11,
        39
    ),
    (
        'skiter',
        'Oliver Lepko',
        'Slovakia',
        'Europe',
        'Carry',
        39,
        291
    ),
    (
        'Aui_2000',
        'Kurtis Daniel Ling',
        'Canada',
        'North America',
        'Coach',
        39,
        284
    ),
    (
        '33',
        'Neta Shapira',
        'Israel',
        'Other',
        'Offlaner',
        39,
        260
    ),
    (
        'Nine',
        'Leon Kirilin',
        'Germany',
        'Europe',
        'Solo Middle',
        39,
        38
    ),
    (
        'Saksa',
        'Martin Sazdov',
        'North Macedonia',
        'Other',
        'Support',
        39,
        245
    ),
    (
        'Sneyking',
        'Wu Jingjun',
        'United States',
        'North America',
        'Support',
        39,
        330
    ),
    (
        'Erika',
        'Yang Shaohan',
        'China',
        'China',
        'Carry',
        65,
        372
    ),
    (
        'Fenrir',
        'Lu Chao',
        'China',
        'China',
        'Coach',
        65,
        377
    ),
    (
        'niu',
        'Li Kongbo',
        'China',
        'China',
        'Offlaner',
        65,
        361
    ),
    (
        'Setsu',
        'Gao Zhenxiong',
        'China',
        'China',
        'Solo Middle',
        65,
        188
    ),
    (
        'fy',
        'Xu Linsen',
        'China',
        'China',
        'Support',
        65,
        254
    ),
    (
        'Yang',
        'Zhou Haiyang',
        'China',
        'China',
        'Support',
        65,
        268
    ),
    (
        'krylat',
        'Alexandr Krylatov',
        'Russia',
        'Europe',
        'Carry',
        54,
        56
    ),
    (
        'Ahilles',
        'Timur Kulmuhambetov',
        'Russia',
        'Europe',
        'Coach',
        54,
        118
    ),
    (
        'Noticed',
        'Evgeniy Ignatenko',
        'Russia',
        'Europe',
        'Offlaner',
        54,
        59
    ),
    (
        'squad1x',
        'Ilya Kuvaldin',
        'Russia',
        'Europe',
        'Solo Middle',
        54,
        224
    ),
    (
        'Dukalis',
        'Andrey Kuropatkin',
        'Russia',
        'Europe',
        'Support',
        54,
        137
    ),
    (
        'illias',
        'Illias Ganeev',
        'Russia',
        'Europe',
        'Support',
        54,
        126
    ),
    (
        'sayuw',
        'Oleg Kalenbet',
        'Russia',
        'Europe',
        'Support',
        54,
        261
    ),
    (
        '.Ark',
        'Yegor Zhabotinskii',
        'Non-representing',
        'Other',
        'Carry',
        12,
        235
    ),
    (
        'Sunlight',
        'Kirill Kachinsky',
        'Belarus',
        'Europe',
        'Offlaner',
        12,
        241
    ),
    (
        'babitich',
        'Vladimir Abelyan',
        'Russia',
        'Europe',
        'Solo Middle',
        12,
        94
    ),
    (
        'FLee',
        'Francis Lee',
        'United States',
        'North America',
        'Support',
        12,
        231
    ),
    (
        'Sammyboy',
        'Samuel Anderson',
        'United States',
        'North America',
        'Support',
        12,
        378
    ),
    (
        'J',
        'Wang Wenjun',
        'China',
        'China',
        'Carry',
        66,
        320
    ),
    (
        'Ghost',
        'Daniel Chan Kok Hong',
        'Malaysia',
        'Southeast Asia',
        'Carry',
        66,
        301
    ),
    (
        'bLink',
        'Zhou Yang',
        'China',
        'China',
        'Coach',
        66,
        18
    ),
    (
        'Srf',
        'Sun Runfa',
        'China',
        'China',
        'Offlaner',
        66,
        367
    ),
    (
        'JT-',
        'Thiay Jun Wen',
        'Malaysia',
        'Southeast Asia',
        'Offlaner',
        66,
        348
    ),
    (
        'Paparazi灬',
        'Zhang Chengjun',
        'China',
        'China',
        'Solo Middle',
        66,
        181
    ),
    (
        'Dy',
        'Ding Cong',
        'China',
        'China',
        'Support',
        66,
        294
    ),
    (
        'Pyw',
        'Xiong Jiahan',
        'China',
        'China',
        'Support',
        66,
        228
    ),
    (
        'ShowTi',
        'Aung Myat Soe',
        'Myanmar',
        'Southeast Asia',
        'Offlaner',
        80,
        333
    ),
    (
        'Lou',
        'Lou Zhen',
        'China',
        'China',
        'Carry',
        67,
        55
    ),
    (
        'Beyond',
        'Xiang Zhenghong',
        'China',
        'China',
        'Offlaner',
        67,
        256
    ),
    (
        '7e',
        'Huang Heming',
        'China',
        'China',
        'Solo Middle',
        67,
        195
    ),
    (
        'zzq',
        'Zhang Ziqiang',
        'China',
        'China',
        'Support',
        67,
        373
    ),
    (
        '天命',
        'Jiang An',
        'China',
        'China',
        'Support',
        67,
        51
    );
INSERT INTO TOURNAMENT(t_name, t_date, t_prize, t_winner)
VALUES ('Caracas Minor', '2017-01-29', 80000, 10),
    ('Brussels Invitational', '2017-02-21', 80000, 39),
    ('Singapore Qualifier', '2017-03-13', 10000, 60),
    ('Athens Open', '2017-03-30', 20000, 78),
    ('Moscow Invitational', '2017-06-10', 50000, 6),
    ('Astana Open', '2017-07-12', 10000, 66),
    ('Tbilisi Minor', '2017-12-14', 150000, 16),
    ('Sarajevo Major', '2018-05-15', 750000, 38),
    ('Minsk Open', '2018-06-05', 20000, 74),
    ('Copenhagen Pro Series', '2018-06-24', 10000, 42),
    (
        'Non-representing Major',
        '2018-07-04',
        760000,
        39
    ),
    ('Montevideo Major', '2018-10-11', 560000, 75),
    ('Chisinau Pro Series', '2018-12-30', 50000, 5),
    ('Sofia Pro Series', '2019-01-26', 10000, 5),
    ('Islamabad Minor', '2019-01-26', 120000, 32),
    ('Amsterdam Major', '2019-02-21', 440000, 69),
    ('Vientiane Minor', '2019-03-31', 170000, 71),
    ('Bishkek Major', '2019-04-22', 720000, 65),
    ('Prague Major', '2019-06-16', 400000, 41),
    ('Lima Pro Series', '2019-08-18', 10000, 22),
    ('Bangkok Minor', '2019-12-04', 70000, 56),
    ('Stockholm Pro Series', '2019-12-10', 30000, 44),
    ('Belgrade Pro Series', '2020-02-11', 40000, 6),
    (
        'Bratislava Invitational',
        '2020-03-07',
        70000,
        28
    ),
    ('Mexico City Qualifier', '2020-03-17', 10000, 77),
    ('Kiev Open', '2020-03-19', 40000, 46),
    ('Jerusalem Qualifier', '2020-03-27', 20000, 5),
    ('Budapest Minor', '2020-06-01', 130000, 23),
    ('Seoul Minor', '2020-07-21', 70000, 7),
    ('Beirut Open', '2020-08-26', 30000, 59),
    ('Shanghai Pro Series', '2020-10-24', 30000, 42),
    ('Tallinn Invitational', '2020-12-17', 90000, 69),
    ('Quito Minor', '2020-12-29', 110000, 71),
    ('Skopje Major', '2021-01-01', 550000, 22),
    ('Amman Qualifier', '2021-01-19', 10000, 2),
    ('London Pro Series', '2021-01-20', 50000, 33),
    ('Naypyidaw Major', '2021-03-02', 640000, 24),
    ('Warsaw Major', '2021-04-04', 700000, 14),
    ('Jakarta Major', '2021-04-18', 380000, 63),
    ('Vienna Open', '2021-05-17', 30000, 21),
    ('Kuala Lumpur Minor', '2021-05-29', 70000, 17),
    ('Managua Major', '2021-05-30', 660000, 17),
    ('Berlin Qualifier', '2021-06-19', 20000, 54),
    ('La Paz Major', '2021-11-01', 340000, 59),
    (
        'New York City Pro Series',
        '2021-12-17',
        40000,
        11
    ),
    ('Sydney Pro Series', '2021-12-18', 20000, 24),
    ('São Paulo Pro Series', '2022-01-19', 10000, 48),
    ('Oslo Major', '2022-02-21', 320000, 64),
    ('Manila Major', '2022-05-17', 650000, 29),
    ('Bucharest Pro Series', '2022-05-21', 10000, 54),
    ('Abu Dhabi Minor', '2022-07-27', 60000, 76),
    ('Ulaanbaatar Major', '2022-08-14', 440000, 24),
    ('Toronto Open', '2022-09-03', 40000, 17),
    (
        'Buenos Aires Pro Series',
        '2022-10-30',
        10000,
        57
    );
-- add team history
INSERT INTO PLAYER_TEAM_HISTORY (player_id, team_id)
SELECT player_id,
    team_id
FROM PLAYER;
-- update team winnings
UPDATE TEAM
SET team_winnings = (
        SELECT sum(t_prize)
        FROM TOURNAMENT
        WHERE TOURNAMENT.t_winner = TEAM.team_id
    );
-- change nulls to 0 in team
UPDATE TEAM
SET team_winnings = 0
WHERE team_winnings IS NULL;